name: pv-manager
services:
  app:
    build:
      context: C:\Users\lesbu\Videos\pv windsurf\gestion_pv\pv-manager
      dockerfile: Dockerfile
    container_name: pv-manager-app
    depends_on:
      postgres:
        condition: service_started
        required: true
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/pv_manager?schema=public
      EMAIL_FROM: onboarding@resend.dev
      EMAIL_FROM_NAME: PV Manager
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXTAUTH_SECRET: your_nextauth_secret_key
      NEXTAUTH_URL: http://localhost:3000
      NODE_ENV: development
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      NPM_CONFIG_STRICT_SSL: "false"
      RESEND_API_KEY: re_9SQGn67u_BE8KgmGLiShiuDnFz2CFa6dY
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:3000/api/health
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 40s
    mem_limit: "4294967296"
    memswap_limit: "4294967296"
    networks:
      pv-network: null
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
    restart: unless-stopped
  postgres:
    container_name: pv-manager-db
    environment:
      POSTGRES_DB: pv_manager
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:14-alpine
    networks:
      pv-network: null
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        volume: {}
networks:
  pv-network:
    name: pv-manager-network
    driver: bridge
volumes:
  postgres_data:
    name: pv-manager-postgres-data
