version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: pv-manager-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pv_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pv-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ilya233/pv-manager:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pv-manager-app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pv_manager?schema=public
      # Désactiver la vérification de l'hôte correspondant pour NextAuth
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your_nextauth_secret_key
      - NEXTAUTH_SECURE=false
      # Cette variable est cruciale pour l'accès externe
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - NODE_ENV=production
      # Paramètres pour ignorer les erreurs SSL (pour le build)
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - NPM_CONFIG_STRICT_SSL=false
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - pv-network
    # Augmenter les limites de mémoire pour éviter les problèmes de build
    mem_limit: 4g
    memswap_limit: 4g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  pv-network:
    name: pv-network

volumes:
  postgres_data:
    name: pv-manager-postgres-data
